site_name: Красные флажки
site_url: https://trofimovelijah.github.io/red-flag-analysis

theme:
  name: material
  language: ru
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections

nav:
  - Главная: index.md
  - Технический проект: technical_project/README.md
  - Вопросы: qa/question.md


plugins:
  - search
  - include-markdown:
#      heading_offset: -1  # Сдвигает заголовки на уровень вверх для единого уровня
      rewrite_relative_urls: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
