site_name: Красные флажки
site_url: https://trofimovelijah.github.io/red-flag-analysis

theme:
  name: material
  language: ru
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections

nav:
  - index.md
  - 01_Idea.md
  - 02_Introduction.md
  - 03_Analysis.md
  - 04_Requirements.md
  - 05_Role.md
  - 06_Architecture.md
  - 07_Database.md

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
