name: Generate PlantUML

on:
  push:
    branches: [ main ]

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PlantUML diagrams
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: docs/dbms
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate PlantUML diagrams"
          file_pattern: "docs/dbms/**"